# analysis/analysis_SimulationLoggingParams_log_file.R
library(ggplot2)
library(dplyr)
library(hadron) # Assuming hadron package is installed and available
source("data_io.R") # Assuming data_io.R is in the working directory

# Simple logger used by analysis scripts
write_log <- function(msg) {
  logfile <- get0("WF_LOG_FILE", ifnotfound = NA)
  if (is.na(logfile)) logfile <- "analysis_debug.log"
  timestamp <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
  cat(sprintf("[%s] %s\n", timestamp, msg), file = logfile, append = TRUE)
}

# Function to calculate exp(-delta_H) and perform bootstrapping
analyze_exp_neg_deltaH <- function(data, out_pdf_prefix, skip_steps = 0) {
  write_log(paste0("analyze_exp_neg_deltaH: start prefix=", out_pdf_prefix, " skip=", skip_steps))
  data <- data %>% mutate(exp_neg_delta_H = exp(-delta_H))

  # Save the plot generated by bootstrap.analysis to a PDF
  out_pdf <- paste0(out_pdf_prefix, "_bootstrap_exp_neg_delta_H.pdf")
  write_log(paste0("analyze_exp_neg_deltaH: saving ", out_pdf))
  tryCatch(
    {
      pdf(out_pdf)
      hadron::bootstrap.analysis(data$exp_neg_delta_H, skip = skip_steps, pl = TRUE)
      dev.off()
      write_log("analyze_exp_neg_deltaH: saved")
    },
    error = function(e) {
      write_log(paste0("analyze_exp_neg_deltaH: ERROR: ", conditionMessage(e)))
    }
  )
}

analyze_acceptance <- function(data, out_pdf_prefix, skip_steps = 0) {
  out_pdf <- paste0(out_pdf_prefix, "_bootstrap_acceptance.pdf")
  write_log(paste0("analyze_acceptance: saving ", out_pdf))
  tryCatch(
    {
      pdf(out_pdf)
      hadron::bootstrap.analysis(data$acceptance, skip = skip_steps, pl = TRUE)
      dev.off()
      write_log("analyze_acceptance: saved")
    },
    error = function(e) {
      write_log(paste0("analyze_acceptance: ERROR: ", conditionMessage(e)))
    }
  )
}

# New: analyze delta_H timeseries and autocorrelation using hadron::uwerrprimary
analyze_deltaH_autocorr <- function(data, out_pdf_prefix, skip_steps = 0) {
  write_log(paste0("analyze_deltaH_autocorr: start prefix=", out_pdf_prefix, " skip=", skip_steps))

  # Ensure delta_H column exists
  if (!"delta_H" %in% names(data)) {
    write_log("analyze_deltaH_autocorr: delta_H column not found in data")
    return(invisible(NULL))
  }

  # Prepare timeseries dataframe (use hmc_step if available)
  step_col <- if ("hmc_step" %in% names(data)) "hmc_step" else names(data)[1]
  ts_df <- data %>%
    transmute(step = as.integer(as.numeric(.data[[step_col]])), delta_H = as.numeric(delta_H)) %>%
    filter(!is.na(step) & !is.na(delta_H))

  # Timeseries plot
  ts_pdf <- paste0(out_pdf_prefix, "_delta_H_timeseries.pdf")
  write_log(paste0("analyze_deltaH_autocorr: saving timeseries to ", ts_pdf))
  tryCatch(
    {
      p <- ggplot(ts_df, aes(x = step, y = delta_H)) +
        geom_line(color = "darkgreen") +
        geom_point(size = 0.7, alpha = 0.6) +
        labs(title = "delta_H vs HMC step", x = "HMC step", y = "delta_H") +
        theme_minimal()
      ggsave(ts_pdf, plot = p, width = 8, height = 3)
      write_log("analyze_deltaH_autocorr: timeseries saved")
    },
    error = function(e) {
      write_log(paste0("analyze_deltaH_autocorr: ERROR saving timeseries plot: ", conditionMessage(e)))
    }
  )

  # Autocorrelation analysis using hadron::uwerrprimary on delta_H after skipping
  n_total <- nrow(ts_df)
  if (skip_steps < 0) skip_steps <- 0
  if (skip_steps >= n_total) {
    write_log(paste0("analyze_deltaH_autocorr: skip_steps (", skip_steps, ") >= available rows (", n_total, ") - skipping autocorr"))
    return(invisible(NULL))
  }

  ac_series <- ts_df$delta_H[(skip_steps + 1):n_total]
  ac_series <- as.numeric(ac_series[!is.na(ac_series)])
  write_log(paste0("analyze_deltaH_autocorr: computing uwerrprimary on ", length(ac_series), " points"))

  if (length(ac_series) < 2) {
    write_log("analyze_deltaH_autocorr: not enough data points for autocorrelation")
    return(invisible(NULL))
  }

  uw_res <- tryCatch(
    {
      hadron::uwerrprimary(ac_series, pl = TRUE)
    },
    error = function(e) {
      write_log(paste0("analyze_deltaH_autocorr: ERROR computing uwerrprimary: ", conditionMessage(e)))
      return(NULL)
    }
  )

  if (is.null(uw_res)) {
    write_log("analyze_deltaH_autocorr: uwerrprimary failed")
    return(invisible(NULL))
  }

  # Save uwerr plot
  ac_pdf <- paste0(out_pdf_prefix, "_delta_H_autocorr.pdf")
  write_log(paste0("analyze_deltaH_autocorr: saving autocorr plot to ", ac_pdf))
  tryCatch(
    {
      pdf(ac_pdf, width = 8, height = 6)
      plot(uw_res)
      dev.off()
      write_log("analyze_deltaH_autocorr: autocorr plot saved")
    },
    error = function(e) {
      write_log(paste0("analyze_deltaH_autocorr: ERROR saving autocorr plot: ", conditionMessage(e)))
    }
  )

  # Write summary
  summary_file <- paste0(out_pdf_prefix, "_delta_H_autocorr_summary.txt")
  tauint <- if (!is.null(uw_res$tauint)) uw_res$tauint else NA
  dtauint <- if (!is.null(uw_res$dtauint)) uw_res$dtauint else NA
  write_log(paste0("analyze_deltaH_autocorr: writing summary to ", summary_file))
  tryCatch(
    {
      cat(sprintf("n_points_after_skip: %d\n", length(ac_series)), file = summary_file)
      cat(sprintf("tauint: %s\n", as.character(tauint)), file = summary_file, append = TRUE)
      cat(sprintf("dtauint: %s\n", as.character(dtauint)), file = summary_file, append = TRUE)
      write_log("analyze_deltaH_autocorr: summary written")
    },
    error = function(e) {
      write_log(paste0("analyze_deltaH_autocorr: ERROR writing summary: ", conditionMessage(e)))
    }
  )

  return(invisible(list(uw = uw_res, tauint = tauint, dtauint = dtauint)))
}

analyze_simulation_log <- function(directory, skip_steps = 0) {
  # Read YAML to get configured filename (base pattern)
  config <- read_yaml_config(directory)
  filename <- config$SimulationLoggingParams$log_filename
  if (is.null(filename) || filename == "") {
    stop("SimulationLoggingParams$log_filename not found in YAML")
  }

  # Build a more specific pattern to avoid matching analysis output files
  # Matches base.txt, base.rank1.txt, etc. but not base_summary.txt
  base_prefix <- sub("\\.txt$", "", filename)
  pattern <- paste0("^", base_prefix, "(\\.(rank[0-9]+))?\\.txt$")

  files <- list.files(directory, pattern = pattern, full.names = TRUE)
  if (length(files) == 0) {
    stop(paste0("No simulation log files found matching pattern '", pattern, "' in directory: ", directory))
  }

  for (f in files) {
    message(paste0("Processing simulation log file: ", f))
    base <- basename(f)
    base_noext <- sub("\\.txt$", "", base)
    out_prefix <- file.path(directory, base_noext)

    # Read the log data and run analyses
    log_data <- read_data_file(f)

    # Call the analyze functions which will create PDFs named using out_prefix
    analyze_exp_neg_deltaH(log_data, out_prefix, skip_steps = skip_steps)
    analyze_acceptance(log_data, out_prefix, skip_steps = skip_steps)
    analyze_deltaH_autocorr(log_data, out_prefix, skip_steps = skip_steps)
  }
}

# Main execution
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2) {
  stop("Usage: Rscript analysis_SimulationLoggingParams_log_file.R <directory> <skip_steps>")
}
directory <- args[1]
skip_steps <- args[2]
logs_dir <- file.path(directory, "logs")
if (!dir.exists(logs_dir)) dir.create(logs_dir, recursive = TRUE)
assign("WF_LOG_FILE", file.path(logs_dir, "analysis_SimulationLoggingParams_log_file.log"), envir = .GlobalEnv)
write_log("analysis_SimulationLoggingParams_log_file.R: starting")
analyze_simulation_log(directory, skip_steps = as.integer(skip_steps))
write_log("analysis_SimulationLoggingParams_log_file.R: finished")
