# analysis/analysis_SimulationLoggingParams_log_file.R
library(ggplot2)
library(dplyr)
library(hadron) # Assuming hadron package is installed and available
source("data_io.R") # Assuming data_io.R is in the working directory

# Function to calculate exp(-delta_H) and perform bootstrapping
analyze_delta_H <- function(data, skip_steps = 0) {
  data <- data %>% mutate(exp_neg_delta_H = exp(-delta_H))

# Save the plot generated by bootstrap.analysis to a PDF
pdf("bootstrap_exp_neg_delta_H.pdf")
bootstrap_results <- hadron::bootstrap.analysis(data$exp_neg_delta_H, skip=skip_steps, pl=TRUE)
dev.off()
}

analyze_acceptance <- function(data, skip_steps = 0) {
  pdf("bootstrap_acceptance.pdf")
  bootstrap_results <- hadron::bootstrap.analysis(data$acceptance, skip=skip_steps, pl=TRUE)
  dev.off()
}

analyze_simulation_log <- function(directory, skip_steps = 0) {
  # Read the simulation log data
  log_data <- read_simulation_log(directory)

  # Call the analyze_delta_H function
  analyze_delta_H(log_data, skip_steps = skip_steps)
  analyze_acceptance(log_data, skip_steps = skip_steps)
}

# Main execution
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2) {
  stop("Usage: Rscript analysis_SimulationLoggingParams_log_file.R <directory> <skip_steps>")
}
directory <- args[1]
skip_steps <- args[2]
analyze_simulation_log(directory, skip_steps = as.integer(skip_steps))